import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    name: "GRAPHICS CAMO BASKETBALL JERSEY",
    product:'cloth',
    category:'men',
    originalPrice: 2999,
    discountedPrice: 1999,
    description: "A BASKETBALL JERSEY WITH CAMO-PRINT DETAILS MADE WITH RECYCLED MATERIALS",
    rating: 4.5,
    avalabelSize: ['XS', 'S', 'M', 'l', 'XL'],
    isBestseller: true,
    isTrending: false,
    imageSource: ["assets/Aloe/photo-1.webp", "assets/Aloe/photo-2.webp"],
    quantity: 15,
    inStock: true
  },
  {
    _id: uuid(),
    name: "NMD_R1 PRIMEBLUE SHOES",
    product:"shoe",
    category:'men',
    originalPrice: 12999,
    discountedPrice: 11999,
    description: "RUNNING SHOES FOR SPEED AND STABILITY.",
    rating: 5,
    avalabelSize: ['5','6','7','8','9','10'],
    isBestseller: true,
    isTrending: true,
    imageSource: ["assets/Aloe/photo-1.webp", "assets/Aloe/photo-2.webp"],
    quantity: 5,
    inStock: true
  },
  {
    _id: uuid(),
    name: "ADIDAS SPRT SHARK WOVEN TRACK JACKET",
    product:"cloth",
    category:'men',
    originalPrice: 7999,
    discountedPrice: 5599,
    description: "A TRACK JACKET WITH AN ARCHIVE-INSPIRED DESIGN THAT'S JUST AS FRESH TODAY.",
    rating: 3.5,
    avalabelSize: ['XS', 'S', 'M', 'l', 'XL'],
    isBestseller: false,
    isTrending: false,
    imageSource: ["assets/Aloe/photo-1.webp", "assets/Aloe/photo-2.webp"],
    quantity: 7,
    inStock: true
  },
  {
    _id: uuid(),
    name: "ADILETTE BONEGA SLIDES",
    product:"shoe",
    category:'women',
    originalPrice: 4999,
    discountedPrice:3499,
    description: "CASUAL ADILETTE SLIDES WITH A CHIC DESIGN.",
    rating: 3.5,
    avalabelSize: ['5','6','7','8','9','10'],
    isBestseller: false,
    isTrending: false,
    imageSource: ["assets/Aloe/photo-1.webp", "assets/Aloe/photo-2.webp"],
    quantity: 15,
    inStock: true
  },
  {
    _id: uuid(),
    name: "REGULAR TEE WITH VELVET STRIPES AND TREFOIL RIVET",
    product:"cloth",
    category:'women',
    originalPrice: 2499,
    discountedPrice: 1999,
    description: "AN EVERYDAY TEE WITH GLAMMED-UP 3-STRIPES.",
    rating: 4.5,
    avalabelSize: ['XS', 'S', 'M', 'l', 'XL'],
    isBestseller: false,
    isTrending: true,
    imageSource: ["assets/Aloe/photo-1.webp", "assets/Aloe/photo-2.webp"],
    quantity: 12,
    inStock: true
  },
  {
    _id: uuid(),
    name: "ZX 1K BOOST SHOES",
    product:"shoe",
    category:'women',
    originalPrice: 7999,
    discountedPrice: 4999,
    description: "MATERIAL-MIX SHOES FOR NON-STOP COMFORT.",
    rating: 4.5,
    avalabelSize:['4','5','6','7','8','9','10'],
    isBestseller: true,
    isTrending: false,
    imageSource: ["assets/Aloe/photo-1.webp", "assets/Aloe/photo-2.webp"],
    quantity: 8,
    inStock: true
  },
  {
    _id: uuid(),
    name: "ADIDAS ZX 8000 X LEGO® SHOES",
    product:"shoe",
    category:'kids',
    originalPrice: 7599,
    discountedPrice: 2999,
    description: "BRING A SENSE OF PLAY TO YOUR DAY WITH THE ADIDAS ZX 8000 X LEGO® SHOES.",
    rating: 5,
    avalabelSize: ['3','4','5','6'],
    isBestseller: true,
    isTrending: true,
    imageSource: ["assets/Aloe/photo-1.webp", "assets/Aloe/photo-2.webp"],
    quantity: 10,
    inStock: true
  },
  {
    _id: uuid(),
    name: "ADIDAS X MARVEL SPIDER-MAN TEE",
    product:"cloth",
    category:'kids',
    originalPrice: 1400,
    discountedPrice: 600,
    description: "AN EVERYDAY TEE WITH GLAMMED-UP MARVEL SPIDER-MAN",
    rating: 3.5,
    avalabelSize: ['XS', 'S', 'M', 'l', 'XL'],
    isBestseller: false,
    isTrending: false,
    imageSource: ["assets/Aloe/photo-1.webp", "assets/Aloe/photo-2.webp"],
    quantity: 12,
    inStock: true
  },
  {
    _id: uuid(),
    name: "GRAND COURT SHOES",
    product:"shoe",
    category:'kids',
    originalPrice: 3599,
    discountedPrice: 2999,
    description: "LOW-PROFILE SHOES INSPIRED BY RETRO SPORT STYLES.",
    rating: 4.5,
    avalabelSize: ['3','4','5','6'],
    isBestseller: false,
    isTrending: true,
    imageSource: ["assets/Aloe/photo-1.webp", "assets/Aloe/photo-2.webp"],
    quantity: 3,
    inStock: true
  },
  
];
